# nginx proxy address - http://172.17.0.1:8000

name: windmill
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghcr.io/windmill-labs/windmill:main
    container_name: windmill-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:8000:8000'
    volumes:
      - './volumes/data/windmill:/data'
    networks:
      - windmill

networks:
  windmill:
    name: windmill
    external: false
